<?php
// This script and data application were generated by AppGini 5.42
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/order_details.php");
	include("$currDir/order_details_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('order_details');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "order_details";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`order_details`.`odID`" => "odID",
		"IF(    CHAR_LENGTH(`orders1`.`OrderID`), CONCAT_WS('',   `orders1`.`OrderID`), '') /* Order ID */" => "OrderID",
		"IF(    CHAR_LENGTH(`products1`.`ProductName`), CONCAT_WS('',   `products1`.`ProductName`), '') /* Product */" => "ProductID",
		"IF(    CHAR_LENGTH(`categories1`.`CategoryName`) || CHAR_LENGTH(`suppliers1`.`CompanyName`), CONCAT_WS('',   `categories1`.`CategoryName`, `suppliers1`.`CompanyName`), '') /* Category */" => "Category",
		"CONCAT('$', FORMAT(`order_details`.`UnitPrice`, 2))" => "UnitPrice",
		"`order_details`.`Quantity`" => "Quantity",
		"CONCAT('$', FORMAT(`order_details`.`Discount`, 2))" => "Discount"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`order_details`.`odID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`order_details`.`UnitPrice`',
		6 => '`order_details`.`Quantity`',
		7 => '`order_details`.`Discount`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`order_details`.`odID`" => "odID",
		"IF(    CHAR_LENGTH(`orders1`.`OrderID`), CONCAT_WS('',   `orders1`.`OrderID`), '') /* Order ID */" => "OrderID",
		"IF(    CHAR_LENGTH(`products1`.`ProductName`), CONCAT_WS('',   `products1`.`ProductName`), '') /* Product */" => "ProductID",
		"IF(    CHAR_LENGTH(`categories1`.`CategoryName`) || CHAR_LENGTH(`suppliers1`.`CompanyName`), CONCAT_WS('',   `categories1`.`CategoryName`, `suppliers1`.`CompanyName`), '') /* Category */" => "Category",
		"CONCAT('$', FORMAT(`order_details`.`UnitPrice`, 2))" => "UnitPrice",
		"`order_details`.`Quantity`" => "Quantity",
		"CONCAT('$', FORMAT(`order_details`.`Discount`, 2))" => "Discount"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`order_details`.`odID`" => "ID",
		"IF(    CHAR_LENGTH(`orders1`.`OrderID`), CONCAT_WS('',   `orders1`.`OrderID`), '') /* Order ID */" => "Order ID",
		"IF(    CHAR_LENGTH(`products1`.`ProductName`), CONCAT_WS('',   `products1`.`ProductName`), '') /* Product */" => "Product",
		"IF(    CHAR_LENGTH(`categories1`.`CategoryName`) || CHAR_LENGTH(`suppliers1`.`CompanyName`), CONCAT_WS('',   `categories1`.`CategoryName`, `suppliers1`.`CompanyName`), '') /* Category */" => "Category",
		"`order_details`.`UnitPrice`" => "Unit Price",
		"`order_details`.`Quantity`" => "Quantity",
		"`order_details`.`Discount`" => "Discount"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`order_details`.`odID`" => "odID",
		"IF(    CHAR_LENGTH(`orders1`.`OrderID`), CONCAT_WS('',   `orders1`.`OrderID`), '') /* Order ID */" => "OrderID",
		"IF(    CHAR_LENGTH(`products1`.`ProductName`), CONCAT_WS('',   `products1`.`ProductName`), '') /* Product */" => "ProductID",
		"IF(    CHAR_LENGTH(`categories1`.`CategoryName`) || CHAR_LENGTH(`suppliers1`.`CompanyName`), CONCAT_WS('',   `categories1`.`CategoryName`, `suppliers1`.`CompanyName`), '') /* Category */" => "Category",
		"CONCAT('$', FORMAT(`order_details`.`UnitPrice`, 2))" => "UnitPrice",
		"`order_details`.`Quantity`" => "Quantity",
		"CONCAT('$', FORMAT(`order_details`.`Discount`, 2))" => "Discount"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'OrderID' => 'Order ID', 'ProductID' => 'Product');

	$x->QueryFrom="`order_details` LEFT JOIN `orders` as orders1 ON `orders1`.`OrderID`=`order_details`.`OrderID` LEFT JOIN `products` as products1 ON `products1`.`ProductID`=`order_details`.`ProductID` LEFT JOIN `categories` as categories1 ON `categories1`.`CategoryID`=`products1`.`CategoryID` LEFT JOIN `suppliers` as suppliers1 ON `suppliers1`.`SupplierID`=`products1`.`SupplierID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "order_details_view.php";
	$x->RedirectAfterInsert = "order_details_view.php";
	$x->TableTitle = "Order Items";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`order_details`.`odID`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  70, 350, 150, 75, 75, 75);
	$x->ColCaption = array("Order ID", "Product", "Category", "Unit Price", "Quantity", "Discount");
	$x->ColFieldName = array('OrderID', 'ProductID', 'Category', 'UnitPrice', 'Quantity', 'Discount');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/order_details_templateTV.html';
	$x->SelectedTemplate = 'templates/order_details_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `order_details`.`odID`=membership_userrecords.pkValue and membership_userrecords.tableName='order_details' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `order_details`.`odID`=membership_userrecords.pkValue and membership_userrecords.tableName='order_details' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`order_details`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: order_details_init
	$render=TRUE;
	if(function_exists('order_details_init')){
		$args=array();
		$render=order_details_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `order_details`.`odID` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery="select sum(`order_details`.`Quantity`) from ".$x->QueryFrom.' '.$QueryWhere;
		$res=sql($sumQuery, $eo);
		if($row=db_fetch_row($res)){
			$sumRow ="<tr class=\"success\">";
			if(!isset($_REQUEST['Print_x'])) $sumRow.="<td class=\"text-center\"><strong>&sum;</strong></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td class=\"text-right\">{$row[0]}</td>";
			$sumRow.="<td></td>";
			$sumRow.="</tr>";

			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	// hook: order_details_header
	$headerCode='';
	if(function_exists('order_details_header')){
		$args=array();
		$headerCode=order_details_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: order_details_footer
	$footerCode='';
	if(function_exists('order_details_footer')){
		$args=array();
		$footerCode=order_details_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>