<?php
// This script and data application were generated by AppGini 5.42
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/shippers.php");
	include("$currDir/shippers_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('shippers');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "shippers";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`shippers`.`ShipperID`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`shippers`.`ShipperID`" => "Shipper ID",
		"`shippers`.`CompanyName`" => "Company Name",
		"`shippers`.`Phone`" => "Phone"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`shippers` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "shippers_view.php";
	$x->RedirectAfterInsert = "shippers_view.php";
	$x->TableTitle = "Shippers";
	$x->TableIcon = "resources/table_icons/cart.png";
	$x->PrimaryKey = "`shippers`.`ShipperID`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  400, 150);
	$x->ColCaption = array("Company Name", "Phone");
	$x->ColFieldName = array('CompanyName', 'Phone');
	$x->ColNumber  = array(2, 3);

	$x->Template = 'templates/shippers_templateTV.html';
	$x->SelectedTemplate = 'templates/shippers_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shippers`.`ShipperID`=membership_userrecords.pkValue and membership_userrecords.tableName='shippers' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shippers`.`ShipperID`=membership_userrecords.pkValue and membership_userrecords.tableName='shippers' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`shippers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: shippers_init
	$render=TRUE;
	if(function_exists('shippers_init')){
		$args=array();
		$render=shippers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: shippers_header
	$headerCode='';
	if(function_exists('shippers_header')){
		$args=array();
		$headerCode=shippers_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: shippers_footer
	$footerCode='';
	if(function_exists('shippers_footer')){
		$args=array();
		$footerCode=shippers_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>